# Generated by Django 5.1.7 on 2025-04-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='total_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='retal_period',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
