# Generated by Django 5.1.7 on 2025-04-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_books_total_rental_alter_books_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='total_rental',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
